### ISSUE TITLE
Using NaN as noDataValue

### ISSUE THREAD

**Issue by nicholasjvoss** [santilland/plotty#20]
I have a raster file that includes NaN values, but it returns false due to the fact that NaN !== Nan :(

_plotty.js:_
```javascript
if (data[i] === this.noDataValue) {
     alpha = 0;
}
```

Is it possible to add support for this?

**Comment by santilland** [comment]
Hi nicholasjvoss,
could you add or send me a small section of the file to have a look?
Are you specifically not using webgl? This would be the codeblock you are referring to (the pure javascript rendering approach)

**Comment by nicholasjvoss** [comment]
Thanks for the quick response!
Here's what I'm using to plot:
```javascript
const plot = new plotty.plot({
            canvas,
            data: this.values,
            width: this.width,
            height: this.height,
            **noDataValue: NaN,**
            useWebGL: false,
            domain: [0, 5],
            colorScale: 'myscale',
        });
```

**Comment by nicholasjvoss** [comment]
To account for 'NaN' values, my proposal is something like this:
```javascript
if (data[i] === this.noDataValue || isNaN(this.noDataValue)) {
     alpha = 0;
}
```

**Comment by santilland** [comment]
I have been considering this a while and NaN is really not ideal to handle, also in the shader.
I would dislike to diverge the functionality of the webgl and non webgl renderings.
It feels like NaN should not be rendered at all in any case, without needing to set it as noDataValue.
Could you imagine for now previous to rendering converting your NaN values to something like Number.MIN_VALUE ?

**Comment by PacoDu** [comment]
Hi, we have experienced the same issue with NaN at work, it's a common no data value for floats in our meteorological data. Handling NaN in plotty would be really nice as converting every NaN values before rendering would cause a huge overhead.

**Comment by santilland** [comment]
All right, good to know! Thanks for the input. I'll investigate more how to handle the NaN value in the shader.

**Comment by santilland** [comment]
NaN is quite an issue for webgl textures, the only information i have found is coming from the standard:
```
 Any representable 16-bit floating-point value is legal as input
    to a GL command that accepts 16-bit floating-point data.  The
    result of providing a value that is not a floating-point number
    (such as infinity or NaN) to such a command is unspecified, but
    must not lead to GL interruption or termination.  Providing a
    denormalized number or negative zero to GL must yield predictable
    results.
```
Which sounds every implementation can handle it however they want, which would mean results may differ depending on the system.
I have done some tests and it seem that i can test for this by checking if the value is smaller then the negative maximum float value (3.402823466e+38) in the shader, it shows the same results as checking for NaN in javascript when not using webgl.
I think i could add this check as it should not conflict with any other normal values.

**Comment by santilland** [comment]
All right, i pushed a commit also with the build with the latest commit (b161a129b41eaa1c0d54e3c26e036de88d0152ff) 
I automatically don't render NaN values (no need to set it as noDataValue) as there is really no correct way of rendering it, so i think it should not be rendered at all.

**Comment by nicholasjvoss** [comment]
Thank you, Santilland! This is great.

**Comment by santilland** [comment]
All right, good to hear! I created a release so i will be closing the ticket, if you have any further points on this feel free to comment and we can reopen it at any time.

**Comment by gpbmike** [comment]
> All right, i pushed a commit also with the build with the latest commit ([b161a12](https://github.com/santilland/plotty/commit/b161a129b41eaa1c0d54e3c26e036de88d0152ff)) I automatically don't render NaN values (no need to set it as noDataValue) as there is really no correct way of rendering it, so i think it should not be rendered at all.

Hi @santilland. I'm curious why you chose two different testing methods for `NaN`.

1. `value < -3.402823466e+38`
2. `data[i] !== data[i]`

And why those over `Number.isNaN`. 

This is not an argument for any particular method, just a curiosity. Thanks for the awesome library. Cheers.

**Comment by santilland** [comment]
Hello @gpbmike, there are two different checks because plotty can use two different rendering methods. The default one being webgl and the second one (more or less as fallback) being 2d canvas context.
For check 1. - it is not completely trivial to check for NaN in a typed array in webgl (although newer versions might have some dedicated functions), checking if the value is outside a specific range seems to do the trick in most cases
For check 2. - I imagine using Number.isNaN should work exactly the same, but i was trying to have as wide as possible browser support without the need of polyfills, Number.isNaN for example does not seem to be supported by Internet explorer.

**Comment by gpbmike** [comment]
Makes sense. Thanks for taking the time to explain.

**Comment by dulldrums** [comment]
Also ran into this issue, it looks like commit (https://github.com/santilland/plotty/commit/b161a129b41eaa1c0d54e3c26e036de88d0152ff) didn't fix it completely. Making a PR with a fix

**Comment by santilland** [comment]
@dulldrums you are right, thanks for the catch and for taking the time to create an example and do a pull request! I'll merge it in a bit and do a release.

**Comment by dulldrums** [comment]
It looks like the PR I made fixed this for me, but I ran into an issue where NaN values were still rendering in chrome on a Windows machine. Made another PR with what I believe is a more complete check.
