### ISSUE TITLE
How is the 'atPoint' work?

### ISSUE THREAD

**Issue by 2496772010** [santilland/plotty#22]
How is the 'atPoint' work,i don't understand the mean of the 'x,y' about .If or not the image or the geocoordinate?

**Comment by santilland** [comment]
Hello @2496772010,
you are not providing much information, plotty allows you to render a two dimensional raster, so the atPoint function returns the value for the specified x and y parameters of the 2D "array" provided.
It is possible you are using another library that makes use of plotty to render geolocated data, in any case plotty does not handle geocoordinates.
Hope this info helps.

**Comment by santilland** [comment]
Ok, i will close this for now, if there is still some questions feel free to ask and we can reopen the issue.
