### ISSUE TITLE
Colour does not correctly scale to domain

### ISSUE THREAD

**Issue by danwild** [santilland/plotty#27]
Version tested: `v0.4.3`

## Observed behaviour
When I use the `domain` property to target a subset of my data, the colour scale does not 'stretch' across the domain properly.

## Expected
If I set `domain: [1, 10]` and I render data that has values of `10` present, I would expect those values to be represented by the uppermost colour on the scale.

I've set up a simple repro here: https://gist.github.com/danwild/de5efaf725cad25b4e6f3c9ba32e702f

E.g. the below image contains data from [7, 10], with the `viridis` scale I would expect cells with value of 10 to be bright yellow (not green)?

![plotty-example](https://user-images.githubusercontent.com/3774647/94876530-3f195980-049b-11eb-9a58-7c72fbb5010e.png)

**Comment by santilland** [comment]
Hello @danwild i missed this issue and now it has been sitting here quite a while, sorry for that.
Thank you for the example. It looks like there is an issue with the pure javascript rendering (when not using webgl). It seems like the highest value of the domain (in this case 10) is being clipped. There is only one cell with the value 10. The rest of the rendering seems as expected. I will have a look to see what can be done.

No WebGL:
![image](https://user-images.githubusercontent.com/4036819/110447693-c27d4d80-80c0-11eb-9169-be9f14378a1f.png)

With WebGL:
![image](https://user-images.githubusercontent.com/4036819/110447631-b5605e80-80c0-11eb-8479-ddb872e0aa19.png)

**Comment by danwild** [comment]
Hey @santilland,

Thanks! Just tested and confirm `0.4.4` has fixed the issue.

Cheers for the rendering tip too! You're right, I was inflating the data to make my example clear - but I recall begrudgingly doing so because the canvas became blurry when scaling up with css width, will have to remember those optimisation settings - sure they'll come in handy sometime :)

**Comment by santilland** [comment]
Great! Glad to hear, thanks for closing the ticket directly.
