### ISSUE TITLE
Colorscales name error

### ISSUE THREAD

**Issue by scku208** [santilland/plotty#29]
Hi, thanks for this library, it help me a lot.
there is just a liitle typo, thank you

**yi**gnbu --> **yl**gnbu
**yi**orrd --> **yl**orrd

  y**i**gnbu: {
    colors: ['#081d58','#253494','#225ea8','#1d91c0','#41b6c4','#7fcdbb','#c7e9b4','#edf8d9','#ffffd9'],
    positions: [0,0.125,0.25,0.375,0.5,0.625,0.75,0.875,1]
  }
  y**i**orrd: {
    colors: ['#800026','#bd0026','#e31a1c','#fc4e2a','#fd8d3c','#feb24c','#fed976','#ffeda0','#ffffcc'],
    positions: [0,0.125,0.25,0.375,0.5,0.625,0.75,0.875,1]
  },

**Comment by santilland** [comment]
Hello @scku208, thank you for pointing this out!
I updated the colorscale names and made a release.
