### ISSUE TITLE
Initialization fails for devices that support WebGL but do not support OES_texture_float

### ISSUE THREAD

**Issue by sfalmo** [santilland/plotty#32]
As far as I understand, if `useWebGL = true` is set (which is the default), plotty tries to load a WebGL context. If this fails, a fallback to a normal 2d canvas should happen. But in certain cases, this does not work.

If your device supports WebGL, a call to `getContext('[experimental-]webgl')` in [`create3DContext`](https://github.com/santilland/plotty/blob/d28fa6e1f0b7a3ae78e77dfe7a66fcb7cf712dbf/src/plotty.js#L20) succeeds. Then it is checked if the WebGL extension `OES_texture_float` is available and only if this is true the rendering context is returned.
Problem is: after a successful call to `getContext('webgl')`, you cannot make a subsequent `getContext('2d')` call on the same canvas, since the latter will always return `null`.
You can try this e.g. with 
```
var canvas = document.createElement("canvas");
var ctx;
ctx = canvas.getContext('webgl');
console.log(ctx);
ctx = canvas.getContext('2d');
console.log(ctx);
```

So, in the [fallback](https://github.com/santilland/plotty/blob/d28fa6e1f0b7a3ae78e77dfe7a66fcb7cf712dbf/src/plotty.js#L267), the context is not properly initialized and the plotty object is not functional since it neither has a WebGL context nor a conventional 2d context.

I guess one would have to find a way of checking WebGL and OES_texture_float support without creating a rendering context. Or do the checks with a dummy canvas.

**Comment by santilland** [comment]
Hello sfalmo, thank you for spotting this. I guess considering this the best/only? approach would be to have a dummy canvas to check if the extension works. As far as i can see only Opera Android (and maybe Firefox for Android) does not support OES_texture_float.
If browser support is more important then performance i would generally go with disabling webgl. I think this is quite a niche issue, is this affecting your work in some way?

**Comment by sfalmo** [comment]
That should work in my opinion. I can test this on Thursday and will report back then.

**Comment by sfalmo** [comment]
I could test this patch now and it works! Thanks for your effort.

**Comment by santilland** [comment]
Great to hear! made the release now. Will close the ticket.
