### ISSUE TITLE
Colorscales with transparency do not work without WebGL

### ISSUE THREAD

**Issue by sfalmo** [santilland/plotty#33]
If no WebGL is used, colorscales like the following, which use transparency, do not display correctly.
```
plotty.addColorScale("clouds", ["#00000000", "#000000ff"], [0, 1]);
```

I think this is because of [this line](https://github.com/santilland/plotty/blob/d28fa6e1f0b7a3ae78e77dfe7a66fcb7cf712dbf/src/plotty.js#L738) in the `render` method, where the value of the colorscale is not considered.

**Comment by santilland** [comment]
Thank you for reporting this and look for the solution, i merged your pull request

**Comment by santilland** [comment]
Your fix was included in latest release, thank you for your effort and help!
