### ISSUE TITLE
Interpolation of some colorscales with transparency fails if using WebGL

### ISSUE THREAD

**Issue by sfalmo** [santilland/plotty#37]
I have defined the following colorscale:
```
plotty.addColorscale("clouds_red", ["#ff000000", "#ff0000ff"], [0, 1]);
```

When `useWebGL = false`, this behaves as expected:
![plotty_webgl_false](https://user-images.githubusercontent.com/52037539/120449873-1f229880-c390-11eb-87e7-1befb2af0375.png)

For `useWebGL = true`, intermediate values get interpolated to strange greyish tones:
![plotty_webgl_true](https://user-images.githubusercontent.com/52037539/120449947-319cd200-c390-11eb-9893-8ba8e42bd217.png)

This issue shows only for non-grey colorscales with transparency.

**Comment by santilland** [comment]
Thank you for spotting this and finding a solution, and for the corresponding pull request :)
I merged it and created a new release.
