### ISSUE TITLE
color scale with arbitrary step sizes

### ISSUE THREAD

**Issue by crawld** [santilland/plotty#41]
I'd like to create a color scale where the steps are geometrically increasing, e.g.:

[0, 1, 5, 10, 50, 100, 1000]

When I try this, the colors are not correct. For example, the color that shows for value 100 is close to the color for 1.

**Comment by crawld** [comment]
i figured it out, sorry for the noise. sometimes you just need to write out the question to find the answer.

i needed to scale my values to the corresponding percentages for the steps.

**Comment by santilland** [comment]
Happy to hear you found a solution, thanks for closing the ticket!
