### ISSUE TITLE
Question: If there a way to get better color gradients between pixels?

### ISSUE THREAD

**Issue by crh3675** [santilland/plotty#53]
I am using this with GeoTiffs in the browser with Leaflet.  I am wondering if there a way to smooth the hard -edges of the output data when applying the colorscales.  
![image](https://user-images.githubusercontent.com/309006/206951598-9817220e-d0b7-4e1d-a7ab-e4ef9348a949.png)

When zooming in. the blocks are definitely more defined and there is no real gradient between the colors 
![image](https://user-images.githubusercontent.com/309006/206951721-38c8946b-5954-4cba-89e9-640fa942bba8.png)

We do some of this with another effort and trying to find a way to get the same sort of gradiented look with a preset color palette 
![image](https://user-images.githubusercontent.com/309006/206951886-31c331f3-35b0-4e4d-a01a-9244136989bb.png)

**Comment by santilland** [comment]
Hello @crh3675 , on the top of my head i would say this is an interpolation issue when zooming in on the data. So leaflet seems to do linear interpolation, which i think makes sense being the most accurate representation of the actual data.
You could try different interpolation methods, although at a quick glance i don't see a way of configuring this in leaflet, here is an example with openlayers (https://openlayers.org/en/latest/examples/interpolation.html). Maybe there are also some antialiasing configurations that can be applied on the canvas.

In any case I would not consider this to be an issue that can be (or should be) solved with plotty.
I hope the pointers could help a little, I will close this issue now, but feel free to reopen it if you would like to continue the discussion.
