### ISSUE TITLE
Option defaults in docs

### ISSUE THREAD

**Issue by gpbmike** [santilland/plotty#7]
It would be nice if the default value for the options was shown in the docs. It looks like you're using something to generate or edit the docs so I didn't think a PR was appropriate.

| Option | Default |
| --- | --- |
| `canvas` | `document.createElement('canvas')` |
| `data` | `undefined` |
| `width` | `options.data[options.data.length - 2]`* |
| `height` | `options.data[options.data.length - 2]`* |
| `datasets` | `undefined` |
| `colorScaleImage` | `undefined` |
| `colorScale` | `'viridis'` |
| `domain` | `[0, 1]` |
| `clampLow` | `true` |
| `clampHigh` | `clampLow`** |
| `noDataValue` | `undefined` |
| `matrix` | `[1, 0, 0, 0, 1, 0, 0, 0, 1 ]` |
| `useWebGL` | `true` |

*When `data` is defined.
**`clampHigh` will default to the value of `clampLow`

**Notes**
- `useWebGL` isn't mentioned currently in the docs.
- I do not understand what the defaults for width and height do.

**Comment by santilland** [comment]
hi, thank you for your comment, sorry for the late response, for some reason this issue fell through the cracks, i'll have a look at updating the docs in relation to this.

**Comment by santilland** [comment]
I updated the defaults in the documentation, i did not add the default info for width and height, as we were using this in a specific solution where we were encoding the size in those positions, but it is not really representative for other use cases. Not sure what a default value might be useful.

**Comment by gpbmike** [comment]
Awesome. Thank you sir. Love this library. 👍

**Comment by santilland** [comment]
Thanks! Happy to hear!
