### ISSUE TITLE
server side?

### ISSUE THREAD

**Issue by khanhankkhan** [santilland/plotty#8]
Hi
Does plotty work server side? when i do `npm install plotty` - under my nodejs server directory and try to import plotty and run node, i get

`/home/ubuntu/c/node_modules/plotty/src/plotty.js:11
import { colorscales } from './colorscales';
^^^^^^`

note: the reason i'm using plotty server side is because i was hoping to convert an 8 band GeoTiff onto a canvas in a simple way with simple RGB values, and then get the Buffer of the canvas to just store the image as a jpg/png buffer.

**Comment by santilland** [comment]
hello khanhankkhan, i have not tried testing this server side. Your use case makes sense. This library is really quick using webgl rendering but it tries to fallback to pure javascript if it is not able to get a webgl context (which i think is not possible yet server side), so im not completely sure this is the best way of doing it.
In any case could you add a little more information to the error, is that the only output? It is a little hard to see what could be going on from that.

**Comment by santilland** [comment]
Hello khanhankkhan, i will close the ticket for now, if you find time to provide some more info please comment here and i can reopen it.
